name: surf_lint_rules
version: 4.0.0
description: Lint rules for "Surf" company for Dart and Flutter projects.
repository: "https://github.com/surfstudio/flutter-surf-lint-rules"
issue_tracker: "https://github.com/surfstudio/flutter-surf-lint-rules/issues"

dependencies:
  flutter_lints: ^5.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"
